[package]
org = "maryamm"
name = "customer_experience_service"
version = "0.1.0"

[build-options]
sticky = true

[[tool.openapi]]
id = "promos"
targetModule = "promos"
filePath = "../../session-1/o2martpromotions_openapi.yaml"
