openapi: 3.0.1
info:
  title: O2martpromotions
  version: 0.1.0
servers:
  - url: "https://10717d68-0b05-4594-95ed-2f4f1c0c26b6-dev.e1-us-east-azure.choreoapis.dev/default/o2mart-promotions-service/v1.0"
paths:
  /promotions:
    get:
      operationId: getPromotions
      parameters:
      - name: loyalty
        in: query
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Promotion'
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
components:
  schemas:
    ErrorPayload:
      required:
      - message
      - method
      - path
      - reason
      - status
      - timestamp
      type: object
      properties:
        timestamp:
          type: string
        status:
          type: integer
          format: int64
        reason:
          type: string
        message:
          type: string
        path:
          type: string
        method:
          type: string
    Promotion:
      required:
      - ends
      - percentage
      - productId
      type: object
      properties:
        productId:
          type: string
        percentage:
          type: integer
          format: int64
        ends:
          type: string
      additionalProperties: false
